#! /usr/bin/env bash

hadoop jar /opt/hadoop/current/share/hadoop/tools/lib/hadoop-streaming-3.3.0.jar \
-file mapper.py-mapper mapper.py \
-file reducer.py -reducer reducer.py \
-input 200704hourly.txt -output output